### PR TITLE
chore: allow setting acl for result bucket

### PR DESCRIPTION
**Pull request by iSWORD**
This solves a problem I'm having:

Error: error updating Athena WorkGroup (AcmeCorpAthena): InvalidRequestException: 1 validation error detected: Value '' at 'configurationUpdates.resultConfigurationUpdates.aclConfiguration.s3AclOption' failed to satisfy constraint: Member must satisfy enum value set: [BUCKET_OWNER_FULL_CONTROL]

### CODE REVIEW

**Comment by jtsaito** [comment]
Hello @iSWORD and thank you for the suggestion!

If this is a bug fix, could you please add a bug report with a full description of how to reproduce the error so that we can make sure we fully understand the problem and evaluate the fix accordingly?

Also, the suggested change will break the current behaviour for existing use cases. If going forward, I would suggest to make the change optional and maintain the current behaviour as default. To do so, a new optional input variable could be used.

**Comment by iSWORD** [comment]
Hi @jtsaito 

Thank you for your prompt response, and sorry for the lack of details on this. I've been having an issue in one of the projects I'm maintaining, and it seems that someone had manually made changes after using this module, I pushed this PR to make sure I don't undo their changes while applying an unrelated fix. I'm not really familiar with this module or Athena.

I have made it optional to change the ACL of the result bucket. Please feel free to ask for further changes to the PR.

Thank you!

**Comment by jtsaito** [comment]
@iSWORD Hello, and thanks for the update and additional information and looked into it some more.

Based on

> someone had manually made changes after using this module

I understand the Athena workgroup was changed outside of Terraform resulting in the error.

I still don't understand how the error was produced. Could you post the Terraform code or whatever other operation that produced the error as well as the output of `aws` CLI output for describing the Athena workgroup (cf. [get-athena-workgroup](https://awscli.amazonaws.com/v2/documentation/api/2.1.21/reference/athena/get-work-group.html))?

As to the proposed change, I now think there is a conceptual mistake. Setting `acl_configuration.s3_acl_option` to `BUCKET_OWNER_FULL_CONTROL` contradicts the `aws_s3_bucket_ownership_controls` hardcoded in this module as quoted below.

https://github.com/babbel/terraform-aws-athena/blob/b77f429b46e271129fb0a2142e1b3635373d2a87/main.tf#L42-L48

The result is a contradiction in requirements. Because of `BucketOwnerEnforced ` only owner policies apply and "ACLs are disabled" (cf. [documentation](https://docs.aws.amazon.com/AmazonS3/latest/userguide/about-object-ownership.html)). But setting`acl_configuration.s3_acl_option` to `BUCKET_OWNER_FULL_CONTROL` results in Athena explicitly setting a canned ACL for every object it writes to the bucket (cf. [documentation](https://docs.aws.amazon.com/athena/latest/APIReference/API_AclConfiguration.html)) to have shared control for the bucket owner and object owner (cf. [documentation](https://docs.aws.amazon.com/AmazonS3/latest/userguide/acl-overview.html#canned-acl)).

As a result the ACLs are set for the objects the workgroups writes into the bucket, but the ACLs are ignored.

I tried the suggested setting within the same account. After that running Athena queries did *not* produce errors. This is because ACL updates will be accepted by effectively ignored under `BucketOwnerEnforced`, the  [documentation](https://docs.aws.amazon.com/AmazonS3/latest/userguide/about-object-ownership.html#object-ownership-overview) states:

> If an object upload includes the bucket-owner-full-control canned ACL, the bucket owner has full control access, and the object writer no longer has full control access.

Although it does not produce errors, having `BucketOwnerEnforced` and `BUCKET_OWNER_FULL_CONTROL` does not make sense.

Thus I believe the suggested change does not make sense but it should be safe to disable the `s3_acl_option` manually in your workgroup. As this is the original state of this module, you should no longer see a diff (although I'm not entirely sure because I don't have the Terraform code). If the intention was to grant access to the object owner via ACL, this should at no point have worked. But you can use policies instead.

Please let me know if you agree with my reasoning.

**Comment by iSWORD** [comment]
Hi @jtsaito, Thank you for your prompt help!

This is the terraform code that I'm working with:

```hcl
module "acme_athena" {
  source  = "babbel/athena/aws"
  version = "~> 3"

  name                           = "AcmeAthena"
  workgroup_bucket               = "acme-workgroup-bucket"
  workspace_bytes_scanned_cutoff = 1099511627776000


  tags = {
    Name = "AcmeAthena"
  }

  resource_specific_tags = {
    s3_bucket = {
      Owner = "AcmeCorp"
    }
    athena_workgroup = {
      Owner        = "AcmeCorp2"
      SomeOtherTag = true
    }
  }
}
```

And when applying, this is the error I'm facing:

```
module.acme_athena.aws_athena_workgroup.this: Modifying... [id=AcmeAthena]
╷
│ Error: error updating Athena WorkGroup (AcmeAthena): InvalidRequestException: 1 validation error detected: Value '' at 'configurationUpdates.resultConfigurationUpdates.aclConfiguration.s3AclOption' failed to satisfy constraint: Member must satisfy enum value set: [BUCKET_OWNER_FULL_CONTROL]
│ {
│   RespMetadata: {
│     StatusCode: 400,
│     RequestID: "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
│   },
│   AthenaErrorCode: "INVALID_INPUT",
│   Message_: "1 validation error detected: Value '' at 'configurationUpdates.resultConfigurationUpdates.aclConfiguration.s3AclOption' failed to satisfy constraint: Member must satisfy enum value set: [BUCKET_OWNER_FULL_CONTROL]"
│ }
│ 
│   with module.acme_athena.aws_athena_workgroup.this,
│   on .terraform/modules/acme_athena/main.tf line 60, in resource "aws_athena_workgroup" "this":
│   60: resource "aws_athena_workgroup" "this" {
```

**Comment by jtsaito** [comment]
@iSWORD Sorry for the delay and thank you for the additional information.

[My earlier](https://github.com/babbel/terraform-aws-athena/pull/39#issuecomment-1883577329) reasoning remains the same: changing the setting by CLI or console to the original value should not have any effect on the permissions effective on the objects in this bucket because of the `BucketOwnerEnforced`  bucket ownership control rule which overrides the canned ACL.

Thus, if you agree, you could (on you own risk) use CLI or AWS Console (Athena -> Workgroups -> Pick you work group -> Edit) to change the value of "Assign bucket owner full control over query results" back to "false", refresh the Terraform state and have an empty plan. Therefore, PR should not be necessary: allowing `BUCKET_OWNER_FULL_CONTROL` and  `BucketOwnerEnforced` at the same time is inconsistent.

If you disagree or would like to suggest a change of scope, please feel free to point it out for further discussion.

**Comment by egarbi** [comment]
@iSWORD is part of the team. We agree this can be closed and leave the bucket resource to be the one in control. As you suggested removing the attribute from the workgroup will give us a clean plan.

**Pull request closed without merging**
