### PR TITLE
Make Module more flexible for an eventual import of resources

### PR DESCRIPTION
**Pull request by egarbi**
# Description

## Conditional Glue DB 
There may be use cases where users don't need a Glue Database to be created. (ie: when implementing [this](https://aws.amazon.com/blogs/mt/visualize-and-gain-insights-into-your-aws-cost-and-usage-with-amazon-managed-grafana/))
For this particular case introducing a conditional for creation is useful.

## S3 Buckets
A prefix is a good idea, but to make it more flexible for users that are trying to import already created buckets into the module a bucket name is required. The prefix will be conditional from now on

> Unrelated Note: I noticed that many variables are named starting with the prefix `workspace_`, but I think the prefix `workgroup` makes more sense. (maybe a typo?)
> Anyway for this reason the new variable introduced here has the proper prefix

## Docs
The readme has been updated automatically using pre-commit hooks and a config file has been submitted for that reason.

### CODE REVIEW

**Review by jtsaito — COMMENTED** [review]
@egarbi Thank you submitting the PR! ... and sorry for the long wait.

I have added a few detailed remarks in the PR.

However, could you please split up this PR into two separate consecutive PRs to keep the changes smaller and single purpose as follows.

- PR 1: only the changes to `main.tf` and corresponding changes in the `variables.tf` and `outputs.tf`
- PR 2: `README.md` and nicer `variables.tf`

Let's exclude the changes to `.gitignore` and `.pre-commit-config.yaml` entirely for the reasons commented inline.

Again, thank you very much for your help!

**Comment by egarbi** [comment]
thanks for the input, I will make the changes as soon as I find the time

**Comment by egarbi** [comment]
> @egarbi Thank you for submitting the PR! ... and sorry for the long wait.
> 
> I have added a few detailed remarks in the PR.
> 
> However, could you please split up this PR into two separate consecutive PRs to keep the changes smaller and single purpose as follows.
> 
> * PR 1: only the changes to `main.tf` and corresponding changes in the `variables.tf` and `outputs.tf`
> * PR 2: `README.md` and nicer `variables.tf`
> 
> Let's exclude the changes to `.gitignore` and `.pre-commit-config.yaml` entirely for the reasons commented inline.
> 
> Again, thank you very much for your help!

PR1 Proposed as #32 
PR2 will come eventually after #32 is merge

**Comment by egarbi** [comment]
PR1 Proposed as https://github.com/babbel/terraform-aws-athena/pull/32
PR2 will come eventually after https://github.com/babbel/terraform-aws-athena/pull/32 is merge

**Pull request closed without merging**
